# Generated by Django 5.0.7 on 2025-07-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tiempo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('desayuno_hora', models.TimeField(blank=True, null=True)),
                ('almuerzo_hora', models.TimeField(blank=True, null=True)),
                ('cena_hora', models.TimeField(blank=True, null=True)),
                ('desayuno', models.IntegerField(blank=True, null=True)),
                ('almuerzo', models.IntegerField(blank=True, null=True)),
                ('cena', models.IntegerField(blank=True, null=True)),
                ('desayuno_saludable', models.IntegerField(blank=True, null=True)),
                ('almuerzo_saludable', models.IntegerField(blank=True, null=True)),
                ('cena_saludable', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosHabitosAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebo_solo_agua_pura', models.IntegerField(blank=True, null=True)),
                ('bebo_8_vasos_agua', models.IntegerField(blank=True, null=True)),
                ('bebidas_con_azucar', models.IntegerField(blank=True, null=True)),
                ('bebo_agua_al_despertar', models.IntegerField(blank=True, null=True)),
                ('bebo_agua_antes_comidas', models.IntegerField(blank=True, null=True)),
                ('bebo_agua_para_dormir', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatosHabitosAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnica_respiraciones_profundas', models.IntegerField(blank=True, null=True)),
                ('tiempo_tecnica_respiraciones', models.IntegerField(blank=True, null=True)),
                ('horario_tecnica_respiraciones_manana', models.IntegerField(blank=True, null=True)),
                ('horario_tecnica_respiraciones_noche', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatosHabitosAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_3_comidas_horario_fijo', models.IntegerField(blank=True, null=True)),
                ('consumo_5_porciones_frutas_verduras', models.IntegerField(blank=True, null=True)),
                ('consumo_3_porciones_proteinas', models.IntegerField(blank=True, null=True)),
                ('ingiero_otros_alimentos', models.IntegerField(blank=True, null=True)),
                ('consumo_carbohidratos', models.IntegerField(blank=True, null=True)),
                ('consumo_alimentos_fritos', models.IntegerField(blank=True, null=True)),
                ('consumo_alimentos_hechos_en_casa', models.IntegerField(blank=True, null=True)),
                ('consumo_liquidos_mientras_como', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatosHabitosDescanso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duermo_7_8_horas', models.IntegerField(blank=True, null=True)),
                ('despertar_durante_noche', models.IntegerField(blank=True, null=True)),
                ('dificultad_sueno_reparador', models.IntegerField(blank=True, null=True)),
                ('horario_sueno_diario', models.IntegerField(blank=True, null=True)),
                ('despertar_horario_diario', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatosHabitosEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizo_actividad_deportiva', models.IntegerField(blank=True, null=True)),
                ('ejercicio_fisico_diario', models.IntegerField(blank=True, null=True)),
                ('practico_deporte_tiempo_libre', models.IntegerField(blank=True, null=True)),
                ('dedicacion_30_minutos_ejercicio', models.IntegerField(blank=True, null=True)),
                ('ejercicio_carrera_bicicleta', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatosHabitosEsperanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_supremo_interviene', models.IntegerField(blank=True, null=True)),
                ('leo_biblia', models.IntegerField(blank=True, null=True)),
                ('practico_oracion', models.IntegerField(blank=True, null=True)),
                ('orar_y_estudiar_biblia_desarrollo_personal', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatosHabitosSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposicion_sol_diaria', models.IntegerField(blank=True, null=True)),
                ('exposicion_sol_horas_seguras', models.IntegerField(blank=True, null=True)),
                ('exposicion_sol_20_minutos', models.IntegerField(blank=True, null=True)),
                ('uso_bloqueador_solar', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatosHabitosTemperancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_bebidas_alcoholicas', models.IntegerField(blank=True, null=True)),
                ('eventos_sociales_alcohol', models.IntegerField(blank=True, null=True)),
                ('consumo_sustancias_estimulantes', models.IntegerField(blank=True, null=True)),
                ('consumo_refrescos_cola', models.IntegerField(blank=True, null=True)),
                ('consumo_cigarrillos', models.IntegerField(blank=True, null=True)),
                ('consumo_comida_chatarra', models.IntegerField(blank=True, null=True)),
                ('pedir_mas_comida', models.IntegerField(blank=True, null=True)),
                ('agregar_mas_azucar', models.IntegerField(blank=True, null=True)),
                ('agregar_mas_sal', models.IntegerField(blank=True, null=True)),
                ('satisfecho_trabajo', models.IntegerField(blank=True, null=True)),
                ('tenso_nervioso_estresado', models.IntegerField(blank=True, null=True)),
                ('tiempo_libre_redes_sociales', models.IntegerField(blank=True, null=True)),
                ('satisfecho_relaciones_sociales', models.IntegerField(blank=True, null=True)),
                ('apoyo_familia_decisiones', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Despertar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dormir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('tiempo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Esperanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_practica', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tiempo', models.IntegerField()),
            ],
        ),
    ]
